FROM rabbitmq:management-alpine

# Define variáveis de ambiente
ENV RABBITMQ_DEFAULT_USER=admin
ENV RABBITMQ_DEFAULT_PASS=admin
ENV RABBITMQ_DEFAULT_VHOST=/

# Expõe as portas
EXPOSE 5672 15672

# Comando padrão
CMD ["rabbitmq-server"]